let timelineZoom=1.5;const timelineScroll=new Map();
let editorSelection={node:null,kind:'all',frame:null};
function baseTimelineMarkup(n){const d=nodeDuration(n),start=Math.max(0,Math.min(d,qteStartTime(n,d)));let at=0;return `<div class="timeline edit-timeline"><div class="timelinehead"><span>时间轴 · 点击片段编辑</span><small>拖动交互片段左端调整触发点</small></div><div class="timeline-ruler" role="slider" aria-label="时间轴定位" tabindex="0">${[0,.25,.5,.75,1].map(v=>`<span>${(v*d).toFixed(1)}s</span>`).join('')}</div><div class="edit-track"><span>▣ 素材</span><div class="edit-lane">${usingBoards(n)?n.frames.map(f=>{const left=at/d*100;at+=f.duration;return `<button class="timeline-item media-item" data-edit-kind="media" data-edit-frame="${esc(f.id)}" style="left:${left}%;width:${f.duration/d*100}%" title="${esc(f.name)}">${esc(f.name)}</button>`}).join(''):`<button class="timeline-item media-item" data-edit-kind="media" style="left:0;width:100%">${esc(n.videoName||'视频素材 · 点击配置 / 替换')}</button>`}</div></div><div class="edit-track"><span>◇ 交互</span><div class="edit-lane interaction-lane"><button class="timeline-item ux-item" data-edit-kind="interaction" style="left:${start/d*100}%;width:${Math.max(1,(d-start)/d*100)}%" title="点击配置；拖动左端改变触发时机"><i class="timeline-trim" title="拖动调整触发时机"></i>${esc(n.type==='qte'?mouseQteTypes[n.qteGesture||'click']:types[n.type])}<small> ${start.toFixed(1)}s · ${n.limit}s 响应</small></button></div></div></div>`}
function selectEditorPart(kind,frame){if(page!=='story')return;editorSelection={node:current().id,kind,frame:frame||null};renderProperties();paintEditorSelection();if(frame){const card=document.querySelector(`#properties [data-sort-id="${CSS.escape(frame)}"]`);card?.scrollIntoView({block:'nearest'})}}
function paintEditorSelection(){const sel=editorSelection.node===current().id?editorSelection.kind:'all';document.querySelectorAll('#editorArea [data-edit-kind]').forEach(el=>el.classList.toggle('is-selected',sel===el.dataset.editKind&&(!editorSelection.frame||el.dataset.editFrame===editorSelection.frame)));document.querySelector('#editorArea .mechanical-qte')?.classList.toggle('ui-selected',sel==='interaction')}
function editorInspector(){if(page!=='story')return;const root=document.querySelector('#properties');if(editorSelection.node!==current().id)editorSelection={node:current().id,kind:'all',frame:null};const kind=editorSelection.kind;root.insertAdjacentHTML('afterbegin',`<div class="inspector-tabs">${[['all','节点'],['media','素材'],['interaction','交互 UI']].map(([k,t])=>`<button data-edit-tab="${k}" class="${kind===k?'active':''}">${t}</button>`).join('')}</div>`);root.querySelectorAll(':scope > .section').forEach(section=>{const media=!!section.querySelector('#uploadVideo,#uploadBoards');const basic=!!section.querySelector('[data-key="name"]');section.hidden=kind==='media'?!media:kind==='interaction'?(media||basic):false});root.querySelector('#deleteNode').hidden=kind!=='all';for(const key of ['duration','trigger','limit','qteTail','qteHold','cinemaLead'])root.querySelectorAll(`[data-key="${key}"]`).forEach(el=>el.closest('.field').hidden=true);root.querySelectorAll('[data-frame-duration]').forEach(el=>el.closest('.field').hidden=true);}
function bindEditorCanvas(){if(page!=='story'||graph)return;bindTimelineScroll();const stage=document.querySelector('#editorArea .stage'),hud=stage?.querySelector('.mechanical-qte');if(hud){hud.classList.add('editable-ui');hud.tabIndex=0;hud.title='拖动调整位置；点击在右侧配置';hud.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();selectEditorPart('interaction');const n=current(),r=stage.getBoundingClientRect(),x=n.x,y=n.y,sx=e.clientX,sy=e.clientY;hud.setPointerCapture(e.pointerId);function move(ev){n.x=+Math.max(5,Math.min(95,x+(ev.clientX-sx)/r.width*100)).toFixed(1);n.y=+Math.max(5,Math.min(95,y+(ev.clientY-sy)/r.height*100)).toFixed(1);hud.style.left=n.x+'%';hud.style.top=n.y+'%';for(const k of ['x','y']){const input=document.querySelector(`#properties [data-key="${k}"]`);if(input)input.value=n[k]}}function end(){hud.removeEventListener('pointermove',move);hud.removeEventListener('pointerup',end);hud.removeEventListener('pointercancel',cancel);save()}function cancel(){n.x=x;n.y=y;hud.style.left=x+'%';hud.style.top=y+'%';end();renderProperties()}hud.addEventListener('pointermove',move);hud.addEventListener('pointerup',end);hud.addEventListener('pointercancel',cancel)});hud.addEventListener('keydown',e=>{const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!delta)return;e.preventDefault();const n=current();n.x=Math.max(5,Math.min(95,n.x+delta[0]));n.y=Math.max(5,Math.min(95,n.y+delta[1]));save();renderArea();renderProperties();document.querySelector('#editorArea .editable-ui')?.focus()})}
 const trim=document.querySelector('.timeline-trim');trim?.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();selectEditorPart('interaction');const n=current(),lane=trim.closest('.edit-lane'),rect=lane.getBoundingClientRect(),duration=nodeDuration(n);trim.setPointerCapture(e.pointerId);function move(ev){const start=Math.max(0,Math.min(duration-.1,(ev.clientX-rect.left)/rect.width*duration));if(n.tailQte&&n.type==='qte'){n.qteTriggerMode='linked-tail';n.trigger=n.qteTail=+(duration-start).toFixed(2)}else n.trigger=+start.toFixed(2);const clip=trim.parentElement;clip.style.left=start/duration*100+'%';clip.style.width=(duration-start)/duration*100+'%';renderProperties()}function end(){trim.removeEventListener('pointermove',move);trim.removeEventListener('pointerup',end);trim.removeEventListener('pointercancel',end);save();renderArea();renderProperties()}trim.addEventListener('pointermove',move);trim.addEventListener('pointerup',end);trim.addEventListener('pointercancel',end)});
 document.querySelector('.timeline-ruler')?.addEventListener('click',e=>{const r=e.currentTarget.getBoundingClientRect(),t=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*nodeDuration(current()),seek=document.querySelector('#seek');seek.value=t;seek.dispatchEvent(new Event('input',{bubbles:true}))});paintEditorSelection();}
document.addEventListener('click',e=>{const part=e.target.closest('[data-edit-kind]');if(part)selectEditorPart(part.dataset.editKind,part.dataset.editFrame);const tab=e.target.closest('[data-edit-tab]');if(tab)selectEditorPart(tab.dataset.editTab)});

function timeHandle(key,value,scale,side='right',extra=''){return `<i class="time-handle ${side}" role="slider" tabindex="0" aria-label="拖动调整 ${key}" aria-valuenow="${value}" data-time-key="${key}" data-time-value="${value}" data-time-scale="${scale}" ${extra}></i>`}
function timingRow(label,key,value,scale,text,cls=''){return `<div class="edit-track timing-track"><span>${label}</span><div class="edit-lane"><div class="timeline-item timing-item ${cls}" style="left:0;width:${Math.min(100,value/scale*100)}%"><span>${text}</span>${timeHandle(key,value,scale)}</div></div><output>${value.toFixed(1)}s</output></div>`}
function timelineMarkup(n){let html=baseTimelineMarkup(n),d=nodeDuration(n),start=Math.max(0,Math.min(d,qteStartTime(n,d))),rows='';html=html.replace('拖动交互片段左端调整触发点','拖动片段边缘调时长 · 方向键微调 0.1 秒');html=html.replace('<i class="timeline-trim" title="拖动调整触发时机"></i>',timeHandle('start',start,d,'left'));
 if(n.type==='choice'){const marker=`<button class="timeline-item ux-item choice-time-marker" data-edit-kind="interaction" style="left:${start/d*100}%;transform:translateX(${start/d>.5?'-100%':'0'})" title="拖动标记调整选项出现时间；点击在右侧编辑选项">${timeHandle('start',start,d,start/d>.5?'right':'left')}分支选项 · ${start.toFixed(1)}s 出现</button>`;html=html.replace(/<button class="timeline-item ux-item"[\s\S]*?<\/button>/,marker).replace('◇ 交互','◇ 分支选项');}
 if(usingBoards(n)){for(const f of n.frames){const tag=`data-edit-frame="${esc(f.id)}"`;const at=html.indexOf(tag);const end=html.indexOf('</button>',at);html=html.slice(0,end)+timeHandle('frame',f.duration,d,'right',`data-time-frame="${esc(f.id)}"`)+html.slice(end)}}else if(!n.video)rows+=timingRow('场景时长','duration',d,Math.max(10,d*1.5),'占位场景');
 if(n.type==='qte'&&n.tailQte)html=html.replace('◇ 交互','◇ 慢放 / QTE');
 if(n.cinemaMode){const {start:cs,end:ce}=cinemaRange(n,d);rows+=`<div class="edit-track timing-track"><span>电影黑边</span><div class="edit-lane"><div class="timeline-item timing-item cinema-item" style="left:${cs/d*100}%;width:${(ce-cs)/d*100}%">${timeHandle('cinemaStart',cs,d,'left')}<span>${cs.toFixed(1)}–${ce.toFixed(1)}s 黑边</span>${timeHandle('cinemaEnd',ce,d)}</div></div><output>${(ce-cs).toFixed(1)}s</output></div>`}

 if(['qte','hotspot'].includes(n.type)){const scale=Math.max(8,n.limit*1.5);rows+=`<div class="timing-divider">操作时间 · 从 QTE 出现开始计时（不受慢放倍速影响）</div><div class="operation-ruler">${[0,.25,.5,.75,1].map(v=>`<span>${(v*scale).toFixed(1)}s</span>`).join('')}</div>`;rows+=timingRow('响应窗口','limit',Number(n.limit),scale,'超时后跳转','response-item');if(n.qteGesture==='hold')rows+=timingRow('长按完成','qteHold',Number(n.qteHold)||1.5,scale,'持续按住','hold-item')}
 html=html.slice(0,-6)+rows+'</div>';const split=html.indexOf('<div class="timeline-ruler"');return html.slice(0,split)+`<div class="timeline-toolbar"><button data-add-cinema>＋ 电影黑边</button><label>缩放 <input id="timelineZoom" aria-label="时间轴缩放" type="range" min="1" max="5" step="0.25" value="${timelineZoom}"></label><span>横向滚动查看 · 拖动两端调整</span></div><div class="timeline-scroll"><div class="timeline-content" style="width:${timelineZoom*100}%">`+html.slice(split,-6)+'</div></div></div>'}
function applyTimelineTime(n,key,value,frame){value=Math.round(value*10)/10;const duration=nodeDuration(n),start=qteStartTime(n,duration);if(key==='start'){value=Math.max(0,Math.min(n.type==='choice'?duration:duration-.1,value));if(n.tailQte&&n.type==='qte'){n.qteTriggerMode='linked-tail';n.trigger=n.qteTail=+(duration-value).toFixed(3)}else n.trigger=value}else if(key==='cinemaEnd')n.cinemaEnd=Math.max((n.cinemaStart||0)+.1,Math.min(duration,value));else if(key==='cinemaStart')n.cinemaStart=Math.max(0,Math.min(cinemaRange(n,duration).end-.1,value));else if(key==='limit'){n.limit=Math.max(1,Math.min(120,value));if(n.qteHold>n.limit)n.qteHold=n.limit}else if(key==='qteHold')n.qteHold=Math.max(.2,Math.min(4,n.limit,value));else if(key==='duration')n.duration=Math.max(1,Math.min(7200,value));else if(key==='frame'){const f=n.frames.find(f=>f.id===frame);if(f)f.duration=Math.max(.5,Math.min(600,value))}repairTiming(project)}
function readTimelineTime(n,key,frame){return key==='start'?qteStartTime(n,nodeDuration(n)):key==='cinemaEnd'?cinemaRange(n,nodeDuration(n)).end:key==='cinemaStart'?cinemaRange(n,nodeDuration(n)).start:key==='frame'?n.frames.find(f=>f.id===frame).duration:n[key]}
document.addEventListener('pointerdown',e=>{const h=e.target.closest('[data-time-key]');if(!h||e.button!==0)return;e.preventDefault();e.stopPropagation();const n=current(),key=h.dataset.timeKey,frame=h.dataset.timeFrame,initial=Number(h.dataset.timeValue),scale=Number(h.dataset.timeScale),sx=e.clientX,width=h.closest('.edit-lane').getBoundingClientRect().width,backup=structuredClone(n);h.setPointerCapture(e.pointerId);const item=h.closest('.timeline-item'),out=h.closest('.edit-track').querySelector('output');function move(ev){applyTimelineTime(n,key,initial+(ev.clientX-sx)/width*scale,frame);const actual=readTimelineTime(n,key,frame);h.setAttribute('aria-valuenow',actual);if(out)out.textContent=actual.toFixed(1)+'s';if(key==='cinemaStart'||key==='cinemaEnd'){const range=cinemaRange(n,nodeDuration(n));item.style.left=range.start/scale*100+'%';item.style.width=(range.end-range.start)/scale*100+'%';if(out)out.textContent=(range.end-range.start).toFixed(1)+'s'}else if(key==='start'){item.style.left=actual/scale*100+'%';if(item.classList.contains('choice-time-marker')){item.style.transform=`translateX(${actual/scale>.5?'-100%':'0'})`;h.classList.toggle('right',actual/scale>.5);h.classList.toggle('left',actual/scale<=.5)}else item.style.width=(scale-actual)/scale*100+'%'}else item.style.width=Math.max(1,actual/scale*100)+'%';item.title=actual.toFixed(1)+' 秒';syncCinema(document.querySelector('#editorArea .stage'),n,Number(document.querySelector('#seek')?.value)||0,nodeDuration(n))}function end(ev){if(ev.type==='pointercancel')Object.assign(n,backup);h.removeEventListener('pointermove',move);h.removeEventListener('pointerup',end);h.removeEventListener('pointercancel',end);save();renderArea();renderProperties()}h.addEventListener('pointermove',move);h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end)},true);
document.addEventListener('keydown',e=>{const h=e.target.closest('[data-time-key]');if(!h||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const key=h.dataset.timeKey,frame=h.dataset.timeFrame;applyTimelineTime(current(),key,Number(h.dataset.timeValue)+(e.key==='ArrowRight'?.1:-.1),frame);save();renderArea();renderProperties();document.querySelector(`[data-time-key="${key}"]${frame?`[data-time-frame="${CSS.escape(frame)}"]`:''}`)?.focus()});

function bindTimelineScroll(){const scroll=document.querySelector('.timeline-scroll'),content=scroll?.querySelector('.timeline-content'),zoom=document.querySelector('#timelineZoom');if(!scroll)return;scroll.scrollLeft=timelineScroll.get(current().id)??(current().type==='choice'&&qteStartTime(current(),nodeDuration(current()))>nodeDuration(current())*.5?scroll.scrollWidth-scroll.clientWidth:0);scroll.addEventListener('scroll',()=>timelineScroll.set(current().id,scroll.scrollLeft));scroll.addEventListener('wheel',e=>{if(e.shiftKey||Math.abs(e.deltaX)>0){e.preventDefault();scroll.scrollLeft+=e.deltaX||e.deltaY}},{passive:false});zoom.addEventListener('input',()=>{timelineZoom=Number(zoom.value);content.style.width=timelineZoom*100+'%'})}
document.addEventListener('click',e=>{if(!e.target.closest('[data-add-cinema]'))return;const n=current();if(!n.cinemaMode){n.cinemaMode=true;n.cinemaStart=0;n.cinemaEnd=nodeDuration(n);n.cinemaSize=n.cinemaSize||6;save();renderArea()}selectEditorPart('interaction')});
