const {chromium}=require('C:/Users/Admin/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright');
const assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
for(const phone of [false,true]){const p=await b.newPage({viewport:phone?{width:844,height:390}:{width:1440,height:900},isMobile:phone,hasTouch:phone});await p.goto('http://127.0.0.1:4173/');await p.waitForSelector('.nodeitem');
for(const mode of ['right','left','up','down','multi','hold']){await p.evaluate(mode=>{document.querySelector('#player').showModal();const n={qteGesture:mode,qteHold:.2,qteClicks:3,qteDistance:60,x:65,y:50,qteHint:'向右闪避',limit:4};document.querySelector('#playerScreen').innerHTML='<div class="stage cinematic" style="height:calc(100dvh - 44px);width:100%;aspect-ratio:auto"><img class="backimage" src="assets/chapter01-04.png">'+mechanicalQteMarkup(n)+'</div>';window.testSuccess=false;window.testCleanup?.();window.testCleanup=bindMouseQte(n,document.querySelector('#playerScreen .stage'),()=>!window.testSuccess,()=>window.testSuccess=true,(text,ratio)=>updateMechanicalQte(document.querySelector('#playerScreen'),text,ratio));},mode);
await p.waitForTimeout(350);const box=await p.locator('#playerScreen .mechanical-qte').boundingBox();assert(box.y>=0&&box.y+box.height<=(phone?390:900),`${mode} clipped`);
if(mode==='right')await p.screenshot({path:`outputs/psd-ui-concepts/L-live-${phone?'phone':'desktop'}.png`});
await p.evaluate(mode=>{const root=document.querySelector('#playerScreen .stage');function emit(type,x,y){root.dispatchEvent(new PointerEvent(type,{pointerId:1,pointerType:matchMedia('(pointer:coarse)').matches?'touch':'mouse',button:0,clientX:x,clientY:y,bubbles:true}))}root.setPointerCapture=()=>{};if(mode==='multi'){for(let i=0;i<3;i++){emit('pointerdown',200,180);emit('pointerup',200,180)}}else{emit('pointerdown',200,180);if(mode!=='hold'){const d={right:[100,0],left:[-100,0],up:[0,-100],down:[0,100]}[mode];emit('pointermove',200+d[0],180+d[1]);emit('pointerup',200+d[0],180+d[1])}}},mode);await p.waitForTimeout(260);assert(await p.evaluate(()=>window.testSuccess),mode+' failed');}
await p.close();}await b.close();console.log('PASS desktop/mobile landscape: six gestures and HUD bounds; screenshots saved')})().catch(e=>{console.error(e);process.exit(1)});
